In [1]:
import pandas as pd

### 导入数据

In [4]:
poverty_ct_2015 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2015.S1701-Data.csv', low_memory=False)
poverty_ct_2016 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2016.S1701-Data.csv', low_memory=False)
poverty_ct_2017 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2017.S1701-Data.csv', low_memory=False)
poverty_ct_2018 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2018.S1701-Data.csv', low_memory=False)
poverty_ct_2019 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2019.S1701-Data.csv', low_memory=False)
poverty_ct_2020 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2020.S1701-Data.csv', low_memory=False)
poverty_ct_2021 = pd.read_csv('../data_for_prediction/ACS_Census tract_poverty_S1701/ACSST5Y2021.S1701-Data.csv', low_memory=False)

age_sex_white_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12A-Data.csv', low_memory=False)
age_sex_black_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12B-Data.csv', low_memory=False)
age_sex_indian_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12C-Data.csv', low_memory=False)
age_sex_asian_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12D-Data.csv', low_memory=False)
age_sex_hawaii_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12E-Data.csv', low_memory=False)
age_sex_other_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12F-Data.csv', low_memory=False)
age_sex_multi_cb = pd.read_csv('../data_for_prediction/Census_census block_age_sex_race/DECENNIALSF12010.P12G-Data.csv', low_memory=False)

In [5]:
#poverty_ct_2021#[poverty_ct_2021['GEO_ID'] == '1000000US06001402800']

### 处理census 2010年数据

In [7]:
datasets1 = {
    "white": age_sex_white_cb,
    "black": age_sex_black_cb,
    "indian": age_sex_indian_cb,
    "asian": age_sex_asian_cb,
    "hawaii": age_sex_hawaii_cb,
    "other": age_sex_other_cb,
    "multi": age_sex_multi_cb
}

# 取出Alameda county的数据
def Alameda(df):
    df = df.iloc[1:, :51]
    df.iloc[:, 2:] = df.iloc[:, 2:].astype(int)
    df.drop_duplicates(subset='GEO_ID', keep='first', inplace=True)
    df['County_ID'] = df['GEO_ID'].apply(lambda x: x.split('US')[1].strip()[:5])
    df = df[df['County_ID'] == '06001']
    return df
    
for key in datasets1:
    datasets1[key] = Alameda(datasets1[key])

Alameda_white_df = datasets1['white']
Alameda_black_df = datasets1['black']
Alameda_indian_df = datasets1['indian']
Alameda_asian_df = datasets1['asian']
Alameda_hawaii_df = datasets1['hawaii']
Alameda_other_df = datasets1['other']
Alameda_multi_df = datasets1['multi']

In [8]:
datasets = {
    "white": Alameda_white_df,
    "black": Alameda_black_df,
    "indian": Alameda_indian_df,
    "asian": Alameda_asian_df,
    "hawaii": Alameda_hawaii_df,
    "other": Alameda_other_df,
    "multi": Alameda_multi_df
}

# 按照组aggregate数据
def process_df(df, prefix):
    df = df.iloc[1:, :51]
    df.iloc[:, 2:] = df.iloc[:, 2:].astype(int)
    df.drop_duplicates(subset='GEO_ID', keep='first', inplace=True)
    df[f'1_1_{prefix}'] = df[f'P012{prefix}007'] + df[f'P012{prefix}008'] + df[f'P012{prefix}009'] + df[f'P012{prefix}010']
    df[f'2_1_{prefix}'] = df[f'P012{prefix}011']
    df[f'3_1_{prefix}'] = df[f'P012{prefix}012']
    df[f'4_1_{prefix}'] = df[f'P012{prefix}013']
    df[f'5_1_{prefix}'] = df[f'P012{prefix}014']
    df[f'6_1_{prefix}'] = df[f'P012{prefix}015']
    df[f'7_1_{prefix}'] = df[f'P012{prefix}016']
    df[f'8_1_{prefix}'] = df[f'P012{prefix}017']
    df[f'9_1_{prefix}'] = df[f'P012{prefix}018'] + df[f'P012{prefix}019']
    df[f'10_1_{prefix}'] = df[f'P012{prefix}020'] + df[f'P012{prefix}021']
    df[f'11_1_{prefix}'] = df[f'P012{prefix}022']
    df[f'12_1_{prefix}'] = df[f'P012{prefix}023']
    df[f'13_1_{prefix}'] = df[f'P012{prefix}024'] + df[f'P012{prefix}025']

    df[f'1_2_{prefix}'] = df[f'P012{prefix}031'] + df[f'P012{prefix}032'] + df[f'P012{prefix}033'] + df[f'P012{prefix}034']
    df[f'2_2_{prefix}'] = df[f'P012{prefix}035']
    df[f'3_2_{prefix}'] = df[f'P012{prefix}036']
    df[f'4_2_{prefix}'] = df[f'P012{prefix}037']
    df[f'5_2_{prefix}'] = df[f'P012{prefix}038']
    df[f'6_2_{prefix}'] = df[f'P012{prefix}039']
    df[f'7_2_{prefix}'] = df[f'P012{prefix}040']
    df[f'8_2_{prefix}'] = df[f'P012{prefix}041']
    df[f'9_2_{prefix}'] = df[f'P012{prefix}042'] + df[f'P012{prefix}043']
    df[f'10_2_{prefix}'] = df[f'P012{prefix}044'] + df[f'P012{prefix}045']
    df[f'11_2_{prefix}'] = df[f'P012{prefix}046']
    df[f'12_2_{prefix}'] = df[f'P012{prefix}047']
    df[f'13_2_{prefix}'] = df[f'P012{prefix}048'] + df[f'P012{prefix}049']

    df = df[['GEO_ID','NAME',f'1_1_{prefix}', f'2_1_{prefix}', f'3_1_{prefix}', f'4_1_{prefix}', f'5_1_{prefix}', f'6_1_{prefix}', f'7_1_{prefix}', f'8_1_{prefix}', f'9_1_{prefix}', f'10_1_{prefix}', f'11_1_{prefix}', f'12_1_{prefix}', f'13_1_{prefix}', f'1_2_{prefix}', f'2_2_{prefix}', f'3_2_{prefix}', f'4_2_{prefix}', f'5_2_{prefix}', f'6_2_{prefix}', f'7_2_{prefix}', f'8_2_{prefix}', f'9_2_{prefix}', f'10_2_{prefix}', f'11_2_{prefix}', f'12_2_{prefix}', f'13_2_{prefix}']]
    return df

prefixes = {
    "white": "A",
    "black": "B",
    "indian": "C",
    "asian": "D",
    "hawaii": "E",
    "other": "F",
    "multi": "G"
}

for key in datasets:
    datasets[key] = process_df(datasets[key], prefixes[key])

In [9]:
# test:
# a = datasets['white'].iloc[:,2:]
# a['sum'] = a.sum(axis=1)
# a['sum'].value_counts()

# a = datasets['white']
# a

In [10]:
# wide form change into long form
def process_dataframe(df):
    long_df = df.melt(id_vars = ["GEO_ID", "NAME"], var_name = "Type", value_name = "Population")
    long_df = long_df.drop(columns = ["NAME"])
    return long_df[long_df['Population'] != 0]

processed_datasets = {}
for key, df in datasets.items():
    processed_datasets[key] = process_dataframe(df)

white_long_df_masked = processed_datasets['white']
black_long_df_masked = processed_datasets['black']
indian_long_df_masked = processed_datasets['indian']
asian_long_df_masked = processed_datasets['asian']
hawaii_long_df_masked = processed_datasets['hawaii']
other_long_df_masked = processed_datasets['other']
multi_long_df_masked = processed_datasets['multi']

### 处理每一年的poverty （census tract level）

In [12]:
poverty_ct_dict = {
    2015:poverty_ct_2015,
    2016:poverty_ct_2016,
    2017:poverty_ct_2017,
    2018:poverty_ct_2018,
    2019:poverty_ct_2019,
    2020:poverty_ct_2020,
    2021:poverty_ct_2021,
}
def process_poverty(year):
    poverty_ct_clean = poverty_ct_dict[year].iloc[1:,:]
    poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
    poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
    poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
    poverty_ct_selected = poverty_ct_clean[['GEO_ID','PER_LOWPOVERTY','S1701_C01_001E']]
    poverty_ct_selected.columns = ['GEO_ID','PER_LOWPOVERTY','total_pop']
    poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
    return poverty_ct_selected

poverty_ct_selected_dict = {}
poverty_ct_selected_dict[2015] = process_poverty(2015)
poverty_ct_selected_dict[2016] = process_poverty(2016)
poverty_ct_selected_dict[2017] = process_poverty(2017)
poverty_ct_selected_dict[2018] = process_poverty(2018)
poverty_ct_selected_dict[2019] = process_poverty(2019)
poverty_ct_selected_dict[2020] = process_poverty(2020)
poverty_ct_selected_dict[2021] = process_poverty(2021)

C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_001E'] = poverty_ct_clean['S1701_C01_001E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['S1701_C01_040E'] = poverty_ct_clean['S1701_C01_040E'].astype(int)
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_clean['PER_LOWPOVERTY'] = poverty_ct_clean['S1701_C01_040E']/poverty_ct_clean['S1701_C01_001E']
C:\Users\jduan\AppData\Local\Temp\ipykernel_21772\3695176536.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_ct_selected['censusTract_GEOID'] = poverty_ct_selected['GEO_ID'].apply(lambda x: x.split('US')[1].strip())

In [13]:
poverty_ct_selected_dict[2015]

                    GEO_ID  PER_LOWPOVERTY  total_pop censusTract_GEOID
1     1400000US06001400100        0.041328       2952       06001400100
2     1400000US06001400200        0.099294       1984       06001400200
3     1400000US06001400300        0.118832       5310       06001400300
4     1400000US06001400400        0.111247       4099       06001400400
5     1400000US06001400500        0.191197       3635       06001400500
...                    ...             ...        ...               ...
8053  1400000US06115040800        0.232318       4171       06115040800
8054  1400000US06115040901        0.319927       3282       06115040901
8055  1400000US06115040902        0.311297       1195       06115040902
8056  1400000US06115041000        0.164425       6988       06115041000
8057  1400000US06115041100        0.332400       4287       06115041100

[8057 rows x 4 columns]

In [14]:
white_long_df_masked

                          GEO_ID    Type Population
6       1000000US060014001001007   1_1_A          9
10      1000000US060014001001011   1_1_A          1
14      1000000US060014001001015   1_1_A          6
16      1000000US060014001001017   1_1_A          2
23      1000000US060014001001024   1_1_A          5
...                          ...     ...        ...
622690  1000000US060014517043005  13_2_A          1
622691  1000000US060014517043006  13_2_A          1
622731  1000000US060019820001018  13_2_A          1
622802  1000000US060019832001053  13_2_A          1
622803  1000000US060019832001054  13_2_A          1

[189467 rows x 3 columns]

In [17]:
datasets2 = {
    "white": white_long_df_masked,
    "black": black_long_df_masked,
    "indian": indian_long_df_masked,
    "asian": asian_long_df_masked,
    "hawaii": hawaii_long_df_masked,
    "other": other_long_df_masked,
    "multi": multi_long_df_masked
}

# poverty_ct_selected_dict[2015]
def add_ctPoverty(df, year):
    df['AGEG5YR'] = df['Type'].apply(lambda x: x.split('_')[0])
    df['_SEX'] = df['Type'].apply(lambda x: x.split('_')[1])
    df['_MRACE1'] = df['Type'].apply(lambda x: x.split('_')[2])
    # white_long_df_masked.loc[18463743] 13-2-A
    df['censusTract_GEOID'] = df['GEO_ID'].apply(lambda x: x.split('US')[1].strip()[:11])
    df['STATE_COUNTY_ID'] = df['GEO_ID'].apply(lambda x: x.split('US')[1].strip()[:5])
    df['_MMSA'] = 36084
    df['STATE'] = 'CA'
    
    df = pd.merge(df,poverty_ct_selected_dict[year][['PER_LOWPOVERTY', 'censusTract_GEOID']], on = 'censusTract_GEOID', how = 'inner')

    df['_MRACE1'] = df['_MRACE1'].replace('A',1)
    df['_MRACE1'] = df['_MRACE1'].replace('B',2)
    df['_MRACE1'] = df['_MRACE1'].replace('C',3)
    df['_MRACE1'] = df['_MRACE1'].replace('D',4)
    df['_MRACE1'] = df['_MRACE1'].replace('E',5)
    df['_MRACE1'] = df['_MRACE1'].replace('F',6)
    df['_MRACE1'] = df['_MRACE1'].replace('G',7)
    return df

for year in range(2015, 2022):
    combined_df = pd.DataFrame()
    
    for key in datasets2:
        processed_df = add_ctPoverty(datasets2[key], year)
        combined_df = pd.concat([combined_df, processed_df], axis=0)
    
    combined_df.to_csv(f'../data_for_prediction/combined/add_ctPoverty_combined_{year}_df.csv', index=False)

### 带入到 fit_model.R 中做预测