### data preprocessing

In [1]:
import pandas as pd
import numpy as np

In [3]:
Oakland_311 = pd.read_csv('../Data/Service_requests_received_by_the_Oakland_Call_Center__OAK_311_.csv')

In [5]:
Oakland_311[['REQCATEGORY',"DESCRIPTION"]].value_counts().index.to_list()

[('ILLDUMP', 'Illegal Dumping - debris, appliances, etc.'),
 ('POLICE', 'Parking - Abandoned Vehicle'),
 ('ILLDUMP', 'Illegal Dumping – mattress/boxspring'),
 ('ABANDONED AUTO', 'Parking - Abandoned Vehicle'),
 ('STREETSW', 'Streets - Potholes/Depression'),
 ('OTHER', 'Code Enforcement'),
 ('GRAFFITI', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('PARKING', 'Parking - Enforcement'),
 ('BLDGMAINT', 'City Bldg - Structural Issue'),
 ('ELECTRICAL', 'Street Light - Outage/Damaged'),
 ('METER_REPAIR', 'Parking - Meter Maintenance'),
 ('PARKS', 'Litter in Parks'),
 ('ILLDUMP', 'Illegal Dumping (report from SeeClickFix)'),
 ('TRAFFIC_ENGIN', 'TE - Traffic Safety (non-emergency)'),
 ('BLDGMAINT', 'City Bldg - Electrical Inside/Outside'),
 ('OTHER', 'Oakland Police - Abandoned Auto'),
 ('SEWERS', 'Sewers - Blockage'),
 ('BLDGMAINT', 'Graffiti in a Park'),
 ('HE_CLEAN', 'Homeless Encampment'),
 ('BLDGMAINT', 'City Bldg - Plumbing'),
 ('ELECTRICAL', 'Traffic Signal - Outage/Damaged'),
 ('HOMELESS EMT', 'Homeless Encampment'),
 ('OTHER', 'Miscellaneous'),
 ('ROW_STREETSW', 'Sidewalk - Damage'),
 ('TRAFFIC', 'Graffiti on Traffic Sign(s)'),
 ('ILLDUMP', 'Litter - Street Litter Container - Overflowing/Mis'),
 ('TREES', 'Tree - Pruning'),
 ('OTHER', 'Graffiti on OTHER'),
 ('TREES', 'Tree - Limb Down'),
 ('STREETSW', 'Streets - Street Deterioration'),
 ('BLDGMAINT', 'City Bldg - Clean / Custodial'),
 ('TREES', 'Tree - Diseased, Dead, Dying, Leaning, or Split'),
 ('OTHER', 'Other City Services (app/web request)'),
 ('FIRE', 'Hazardous Materials'),
 ('BLDGMAINT', 'City Bldg - Key / Lock Management'),
 ('ILLDUMP', 'Illegal Dumping – green waste'),
 ('OTHER', 'Human Waste in Public-Right-of-Way'),
 ('DRAINAGE', 'Storm Drains - Clogged (Flooding)'),
 ('DRAINAGE', 'Storm Drains - Clogged (Not Flooding)'),
 ('TREES', 'Tree - Down'),
 ('OTHER', 'Animal and Insect Control'),
 ('TRAFFIC', 'Traffic - Sign Down'),
 ('ILLDUMP', 'Volunteer - Community Bag Pick Up'),
 ('CUT_CLEAN', 'Weed Abatement - Public Right of Way'),
 ('TRAFFIC', 'Traffic - Sign Damage'),
 ('RECYCLING', 'Recycling Hotline - Miscellaneous'),
 ('ILLDUMP', 'Homeless Encampment'),
 ('KOCB', 'Street Cleaning'),
 ('TRAFFIC', 'Traffic - Repair Pavement Striping'),
 ('PARKS', 'Park - Landscape Maintenance'),
 ('OTHER', 'Caltrans issue'),
 ('ILLDUMP', 'Litter - Street Litter Container - Broken'),
 ('ILLDUMP', 'Litter - Green Bag Pickup'),
 ('HE_CLEAN', 'Homeless Encampment - Living in Vehicle'),
 ('GRAFFITI', 'Graffiti on Private Property'),
 ('GRAFFITI', 'Graffiti (report from SeeClickFix)'),
 ('ILLDUMP', 'Illegal Dumping (Enforcement Potential)'),
 ('BLDGMAINT', 'City Bldg - Heating, Ventilation, and Cooling'),
 ('KOCB', 'Street Cleaning - Complaints'),
 ('TRAFFIC', 'Traffic - Sign Missing'),
 ('ELECTRICAL', 'Pedestrian Signal - Broken/Damaged'),
 ('STREETSW', 'Pothole (report from SeeClickFix)'),
 ('OTHER', 'EBMUD issue'),
 ('OTHER', 'Parking - Refund'),
 ('KOCB', 'Litter - Street Litter Container - Overflowing/Mis'),
 ('BLDGMAINT', 'Graffiti on a City Building (Library, Rec Center)'),
 ('RECYCLING', 'Trash/Compost - Abandoned Container'),
 ('OTHER', 'Other (report from SeeClickFix'),
 ('TREES', 'Tree - Broken/Hanging Limb'),
 ('STREETSW', 'Streets/Sidewalks - Curb & Gutter Repair'),
 ('ROW_INSPECTORS', 'Inspections - Utility-Related Infrastructure'),
 ('BLDGMAINT', 'Park - Tot Lots, Tables, Benches'),
 ('HOMELESS EMT', 'Homeless Encampment - Living in Vehicle'),
 ('ROW_INSPECTORS', 'Obstruction (not Construction) Street/Sidew/Parkin'),
 ('DRAINAGE', 'Board Up'),
 ('PARKS', 'Street Medians (Landscaped)'),
 ('BLDGMAINT', 'Park - Plumbing'),
 ('SEWERS', 'Streets - Potholes/Depression'),
 ('ILLDUMP', 'Litter - Street Litter Container'),
 ('ROW_INSPECTORS', 'Inspections - Construction Obstructing ROW'),
 ('TRAFFIC_ENGIN', 'TE - Traffic Signal Request (non-emergency)'),
 ('BLDGMAINT', 'City Bldg - Appliance Issue'),
 ('PARKS', 'Parks - Irrigation'),
 ('GRAFFITI', 'Graffiti on Street Litter Container'),
 ('BLDGMAINT', 'Park - Lighting'),
 ('RECYCLING', 'Recycling - Missed Pickup'),
 ('RECYCLING', 'Recycling/Trash/Compost – Billing Question/Concern'),
 ('GRAFFITI', 'Graffiti - Advertising (posters, signs, etc.)'),
 ('RECYCLING', 'Recycle - Abandoned Cart'),
 ('ENVIRON_ENF', 'Illegal Dumping (Enforcement Potential)'),
 ('PARKING', 'Parking (On Street)'),
 ('KOCB', 'Litter - Street Litter Container - Broken'),
 ('RECYCLING', 'Recycling Service Issue (Residential)'),
 ('PARKS', 'Homeless Encampment'),
 ('TRAFFIC_ENGIN', 'Parking - Enforcement'),
 ('BLDGMAINT', 'City Bldg - Painting'),
 ('TRAFFIC', 'Graffiti on Traffic Paint'),
 ('ROW', 'Inspections - Utility-Related Infrastructure'),
 ('RECYCLING', 'Construction and Demolition Recycling'),
 ('BLDGMAINT', 'City Bldg - Other/Complex'),
 ('BLDGMAINT', 'City Bldg - Pest'),
 ('ROW_INSPECTORS', 'Utility - Lid - Missing or Broken'),
 ('ROW_INSPECTORS', 'ROW - Inspectors - Other/Complex'),
 ('OTHER', 'Vector Control issue'),
 ('OTHER', 'Engineering - Other/Complex'),
 ('SEWERS', 'Manhole Cover - Missing'),
 ('PARKS', 'Parks and Street Medians - Irrigation'),
 ('BLDGMAINT', 'City Bldg - Fence'),
 ('DRAINAGE', 'Storm Drains - Other/Complex'),
 ('PARKS', 'Park - Mowing'),
 ('PARKING', 'TE - Parking (On Street)'),
 ('PARKING', 'Parking - Blue Curb (Residential)'),
 ('ELECTRICAL', 'Electrical - Street Light (report from SeeClickFix'),
 ('BLDGMAINT', 'Park - Fence'),
 ('STREETSW', 'Sidewalk - Damage'),
 ('SIDESHOWS', 'Sideshows - Sideshow Prevention'),
 ('OTHER', 'Bus Bench or Bus Shelter Issue'),
 ('OTHER', 'Streets - Slow Streets'),
 ('TRAFFIC_ENGIN', 'TE - Parking (On Street)'),
 ('TRAFFIC_ENGIN', 'Traffic Engineering - Other/Complex'),
 ('RECYCLING', 'Recycling - Repair/Replace Cart'),
 ('RECYCLING', 'Trash - Missed Pickup'),
 ('SEWERS', 'Sewers - Bad Odor'),
 ('BLDGMAINT', 'City Bldg - Alarms'),
 ('OTHER', 'Engineering Issues'),
 ('OTHER', 'Union Pacific issue'),
 ('BLDGMAINT', 'Park - Sign'),
 ('RECYCLING', 'Trash Service Issue'),
 ('STREETSW', 'Sidewalk (report from SeeClickFix)'),
 ('TRAFFIC_ENGIN', 'TE - Parking - Blue Curb (Residential)'),
 ('ROW_INSPECTORS', 'Contractor Blocking Street/Sidewalk/Parking'),
 ('RECYCLING', 'Compost - Missed Pickup'),
 ('DRAINAGE', 'Storm Inlet Grate - Damaged/Missing'),
 ('OTHER', 'COVID-19 Question'),
 ('PARKS', 'Park Maintenance (report from SeeClickFix)'),
 ('STREETSW', 'Street Issue (report from SeeClickFix)'),
 ('PARKS', 'Park - Pathways, Hardscape and Paving'),
 ('SEWERS', 'Sewers - General'),
 ('ELECTRICAL', 'Street Light - LED Installation Issue'),
 ('KOCB', 'Street Cleaning - Schedule'),
 ('RECYCLING', 'Trash - Cart Repair/Replace'),
 ('RECYCLING', 'CityBldg - Container Req (Cart/Bin from WMAC/CWS)'),
 ('ILLDUMP', 'Illegal Dumping/Litter - Other/Complex'),
 ('OTHER', 'Oakland Police Department'),
 ('BLDGMAINT', 'City Bldg - Sign'),
 ('TREES', 'Tree - Request for Removal'),
 ('TREES', 'Tree - Permit - Waiver'),
 ('TREES', 'Tree - Illegal Tree Removal'),
 ('ROW', 'Sidewalk - Damage'),
 ('RECYCLING', 'Recycling - Cart Request'),
 ('ELECTRICAL', 'Street Light - Pole Down'),
 ('TRAFFIC_ENGIN', 'TE - Traffic Control Plan Review'),
 ('ROW_INSPECTORS', 'Construction Issue - Sidewalk Blocked'),
 ('TREES', 'Tree - Stump Removal'),
 ('RECYCLING', 'Compost - Repair/Replace Cart'),
 ('BLDGMAINT', 'City Bldg - Elevators'),
 ('RECYCLING', 'Recycling - Oil Kit Request'),
 ('PARKS', 'Park - Ballfields'),
 ('ELECTRICAL', 'Traffic Signal (report from SeeClickFix'),
 ('STREETSW', 'Streets - Mudslides/Landslides'),
 ('ROW_INSPECTORS', 'Utility - Wire - Down'),
 ('ILLDUMP', 'Shrine Removal With OPD'),
 ('ELECTRICAL', 'Traffic - Signals - Timing Change Request NON EMER'),
 ('WATERSHED', 'Storm Drains - Illicit Discharge'),
 ('RECYCLING', 'Trash - Schedule Bulky Pickup'),
 ('OTHER', 'PG&E'),
 ('TREES', 'Tree - Other/Complex'),
 ('STREETSW', 'Streets - Guardrail Repair'),
 ('STREETSW', 'Streets/Sidewalks - Pooling Water'),
 ('ROW_INSPECTORS', 'Utility - Trench - Paving Issue'),
 ('ROW_STREETSW', 'Inspections - Curb Ramps'),
 ('ILLDUMP', 'Illegal Dumping - Vehicle Cleanout for OPD'),
 ('ELECTRICAL', 'Street Light - Request for New/Upgrade'),
 ('ROW', 'Inspections - Utility Wire'),
 ('OTHER', 'Graffiti - Other/Complex Issue'),
 ('RECYCLING', 'Recycling Service Issues'),
 ('ROW_INSPECTORS', 'Construction Issue - Street or Bike Lane Blocked'),
 ('ELECTRICAL', 'Electrical Curb Box - Damaged/Missing'),
 ('STREETSW', 'Streets/Sidewalks - Other/Complex'),
 ('ELECTRICAL', 'Traffic Signal - Turned in Wrong Direction'),
 ('OTHER', 'AC Transit'),
 ('TRAFFIC', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('RECYCLING', 'Trash - Bulky Missed Pickup'),
 ('TRAFFIC', 'Traffic - Other/Complex'),
 ('PARKS', 'Park - Other/Complex'),
 ('RECYCLING', 'Garbage - Bulky Pickup'),
 ('GRAFFITI', 'Graffiti in a Park'),
 ('ROW_INSPECTORS', 'Inspections - Utility Wire'),
 ('ROW_INSPECTORS', 'Utility - Wire - Low-Hanging'),
 ('RECYCLING', 'Trash - Bulky Services'),
 ('RECYCLING', 'Recycling - Cart Replaced Incorrectly'),
 ('RECYCLING', 'Compost - Cart Request'),
 ('ROW_INSPECTORS', 'Right of Way - Other/Complex'),
 ('ELECTRICAL', 'Traffic Signal - Knocked Down'),
 ('ROW_INSPECTORS', 'Obstruction (Construction) - Sidewalk'),
 ('ROW', 'Inspections - Construction Obstructing ROW'),
 ('RECYCLING', 'Compost - Food Pail Request'),
 ('OTHER', 'Kudos and Compliments'),
 ('SEWERS', 'Sewers - Other/Complex'),
 ('ROW_INSPECTORS', 'Construction Issue - Parking Blocked'),
 ('TREES', 'Trees (report from SeeClickFix'),
 ('RECYCLING', 'Garbage Service Issue (not at City facility)'),
 ('RECYCLING', 'Trash - Pre-6am Residential Collection'),
 ('ROW_INSPECTORS', 'Inspections - Sewer Lateral'),
 ('TRAFFIC', 'Traffic - Sign (report from SeeClickFix'),
 ('CW_DIT_GIS', 'Cityworks Config Request - SR Template - Change'),
 ('PARKING', 'TE - Parking - Blue Curb (Residential)'),
 ('RECYCLING', 'CityBldg - Missed Garbage Pickup from WMAC'),
 ('RECYCLING', 'Recycling - Missed Pickup - Whole Block'),
 ('BLDGMAINT', 'Parks - Tennis Court Maintenance'),
 ('RECYCLING', 'Trash - Exemption'),
 ('RECYCLING', 'Business - Recycling Technical Assistance'),
 ('ELECTRICAL', 'Electrical Services - Other/Complex'),
 ('RECYCLING', 'Recycling Hotline - Pub Ed Materials'),
 ('PARKING', 'Parking - Residential Permit'),
 ('ILLDUMP', 'Litter - Street Litter Container - Cleaning Needed'),
 ('RECYCLING', 'Trash - Cart Request/New Service'),
 ('STREETSW', 'Streets - Mudslides / Landslides'),
 ('BLDGMAINT', 'City Bldg - Other'),
 ('OTHER', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('ROW_INSPECTORS', 'Obstruction (Construction) - Street or Bike Lane'),
 ('STREETSW', 'Streets - Berm Repair or Install'),
 ('OTHER', 'Homeless Encampment'),
 ('GRAFFITI', 'Graffiti on OTHER'),
 ('RECYCLING', 'Business - Polystyrene'),
 ('RECYCLING', 'Garbage - Missed Pickup'),
 ('OTHER', 'Port of Oakland Issue'),
 ('BLDGMAINT', 'Park - Pathways, Hardscape and Paving'),
 ('ROW_STREETSW', 'ROW - Streets and Sidewalks - Other/Complex'),
 ('TRAFFIC_ENGIN', 'Traffic - Repair Pavement Striping'),
 ('STREETSW', 'Streets/Sidewalks - Pathway Repair'),
 ('DRAINAGE', 'Storm Drains (report from SeeClickFix'),
 ('RECYCLING', 'Garbage - Cart Replaced Incorrectly'),
 ('RECYCLING', 'Compost Service Issue'),
 ('ELECTRICAL', 'Pedestrian Signal - Knocked Down'),
 ('RECYCLING', 'Yard Trimmings - Missed Pickup'),
 ('RECYCLING', 'Recycling - Missed Pickup - Backyard'),
 ('TRAFFIC', 'Graffiti (report from SeeClickFix)'),
 ('RECYCLING', 'Garbage - Exemption Request - weekly/shared'),
 ('PARKS', 'Illegal Dumping - debris, appliances, etc.'),
 ('RECYCLING', 'Trash - Cart Replaced Incorrectly'),
 ('RECYCLING', 'Yard Trimmings - Repair/Replace Cart'),
 ('STREETSW', 'Streets/Sidewalks - Curb &amp; Gutter Repair'),
 ('RECYCLING', 'Yard Trimmings - Cart Replaced Incorrectly'),
 ('TREES', 'Tree - Restake'),
 ('STREETSW', 'Fence - Repair or Install Along Street'),
 ('RECYCLING', 'Garbage - Cart Repair/Replace'),
 ('METER_REPAIR', 'Graffiti on OTHER'),
 ('OTHER', 'Weed Abatement - Public Right of Way'),
 ('PARKING', 'City Parking Garage Issue'),
 ('RECYCLING', 'Recycling - Events'),
 ('KOCB', 'Litter in Parks'),
 ('ELECTRICAL', 'Necklace of Lights Broken/Damaged'),
 ('OTHER', 'Inspections - Utility-Related Infrastructure'),
 ('FIRE', 'Vegetation Management'),
 ('STREETSW', 'Streets - Speed Bump Repair'),
 ('RECYCLING', 'Compost - Xmas Tree Recycling'),
 ('ROW_INSPECTORS', 'Obstruction (Construction) - Parking'),
 ('CW_DIT_GIS', 'Cityworks Config Request - Inbox-Crew Configure'),
 ('ELECTRICAL', 'Street Light - Pole Leaning'),
 ('FIRE', 'Vegetation Mgmt - Complaints (Fire Hazard)'),
 ('PARKING', 'Parking - Blue Curb (Non-Residential)'),
 ('RECYCLING', 'Compost - Missed Pickup - Backyard'),
 ('FIRE', 'Vegetation Mgmt - Pickup Request'),
 ('STREETSW', 'Streets/Sidewalks - Cross-Culvert Repair'),
 ('ROW_INSPECTORS', 'Utility - Trench or Steel Plate - Cover Issue'),
 ('OTHER', 'Graffiti (report from SeeClickFix)'),
 ('PARKS', 'Street Median - Irrigation'),
 ('SEWERS', 'Sewers - Easement'),
 ('DRAINAGE', 'Watershed - Illegal Dumping in a Creek'),
 ('RECYCLING', 'Compost - Missed Pickup - Whole Block'),
 ('ROW_INSPECTORS', 'Utility - Pole - Damaged or Leaning'),
 ('ELECTRICAL', 'Traffic Signal - Pole Leaning/Damaged'),
 ('PARKS', 'Park - Pests'),
 ('RECYCLING', 'Yard Trimmings Service Issue'),
 ('RECYCLING', 'Garbage - Cart Request/New Service'),
 ('TRAFFIC_ENGIN', 'TE - Traffic - Research / Data Requests'),
 ('METER_REPAIR', 'Parking Meter - Other/Complex'),
 ('TRAFFIC_ENGIN', 'TE - Parking - Residential Permit'),
 ('PARKS', 'Volunteer - Community Bag Pick Up'),
 ('SEWERS', 'Inspections - Sewer Lateral'),
 ('RECYCLING', 'Compost - Cart Replaced Incorrectly'),
 ('WATERSHED', 'Watershed and Creeks - Other/Complex'),
 ('PARKS', 'Weed Abatement - Public Right of Way'),
 ('RECYCLING', 'Business - Small Business Start Recycling'),
 ('SEWERS', 'Streets/Sidewalks - Other/Complex'),
 ('RECYCLING', 'Trash - Missed Pickup - Whole Block'),
 ('CUT_CLEAN', 'Cut & Clean - Other/Complex'),
 ('OTHER', 'test template'),
 ('ROW_INSPECTORS', 'Utility - Wire - Shoe on Wire'),
 ('ROW', 'Right of Way - Other/Complex'),
 ('TREES', 'Park - Landscape Maintenance'),
 ('FIRE', 'Fire - Blue Dots'),
 ('RECYCLING', 'Garbage - Pre-6am Residential Collection'),
 ('FIRE', 'Fire - Other/Complex'),
 ('ELECTRICAL', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('TRAFFIC_ENGIN', 'TE - Parking - Blue Curb (Non-Residential)'),
 ('GRAFFITI', 'Graffiti on a City Building (Library, Rec Center)'),
 ('OTHER', 'Graffiti on Bus Bench (not part of a shelter)'),
 ('RECYCLING', 'CityBldg - Missed Compost Pickup'),
 ('RECYCLING', 'Spillage - Trash, Recycle, Compost Spillage'),
 ('STREETSW', 'Streets/Sidewalks Maintenance - General'),
 ('DRAINAGE', 'Watershed - Vegetation Management in a Creek'),
 ('RECYCLING', 'Trash - Missed Pickup - Backyard'),
 ('RECYCLING', 'Yard Trimmings - Food Pail Request'),
 ('RECYCLING', 'Recycling - Contamination Question/Concern'),
 ('RECYCLING', 'Recycling/Garbage - Misc Billing Question/Concern'),
 ('OTHER', 'Graffiti on Private Property'),
 ('CW_DIT_GIS', 'Cityworks Config Request - SR Template - New'),
 ('PARKS', 'Graffiti in a Park'),
 ('DRAINAGE', 'Watershed - Other/Complex'),
 ('SEWERS', 'Sewers (report from SeeClickFix'),
 ('ILLDUMP', 'Litter - In Public Right of Way'),
 ('METER_REPAIR', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('CW_DIT_GIS', 'Cityworks Config Request - WO Template - New'),
 ('OTHER', 'Other Engineering Issues'),
 ('TREES', 'Weed Abatement - Public Right of Way'),
 ('TRAFFIC_ENGIN', 'City Parking Garage Issue'),
 ('RECYCLING', 'Yard Trimmings - Cart Request'),
 ('RECYCLING', 'Recycling - Pre-6am Residential Recycling Collecti'),
 ('TREES', 'Tree - Street Tree Planting'),
 ('DRAINAGE', 'Storm Drains - General'),
 ('OTHER', 'Graffiti on Traffic Sign(s)'),
 ('OTHER', 'Inspections - Utility Wire'),
 ('RECYCLING', 'Litter Container - Missed Pickup'),
 ('RECYCLING', 'Recycling Hotline - Misc - Property Damage'),
 ('GRAFFITI', 'Graffiti - Other/Complex Issue'),
 ('ROW_STREETSW', 'Sidewalk - Damage - ADA Request'),
 ('PARKING', 'Parking - Other/Complex'),
 ('WATERSHED', 'Watershed - Creek Vegetation Management Needed'),
 ('ROW_STREETSW', 'Inspections - Sewer Lateral'),
 ('FIRE', 'Weed Abatement - Public Right of Way'),
 ('PARKS', 'Graffiti (report from SeeClickFix)'),
 ('ROW_STREETSW', 'Sidewalk - Damage - No-Cost Repair Request'),
 ('DRAINAGE', 'Storm Drains - Erosion Control'),
 ('HE_CLEAN', 'Litter in Parks'),
 ('RECYCLING', 'CityBldg - Missed Recycling Pickup from CWS'),
 ('GRAFFITI', 'Code Enforcement'),
 ('DRAINAGE', 'Manhole Cover - Missing'),
 ('CW_DIT_GIS', 'Cityworks Config Request - New Employee'),
 ('PARKING', 'TE - Parking - Residential Permit'),
 ('BLDGMAINT', 'Parks - Irrigation'),
 ('BLDGMAINT', 'City Bldg - Emergency Generators'),
 ('PARKS', 'Park - Plumbing'),
 ('RECYCLING', 'Garbage Service Issue (Residential)'),
 ('OTHER', 'Graffiti on Bus Shelters'),
 ('TRAFFIC', 'City Parking Garage Issue'),
 ('ROW_STREETSW', 'Right of Way - Other/Complex'),
 ('RECYCLING', 'Recycling - Oil Kit Not Replaced'),
 ('FIRE', 'Vegetation Mgmt - Chipping Request'),
 ('TRAFFIC_ENGIN', 'Traffic - Sign Missing'),
 ('ILLDUMP', 'Litter in Parks'),
 ('ELECTRICAL', 'Street Light - Fixture Hanging By Wires'),
 ('ABANDONED AUTO', 'Parking - Abandoned Vehicle - Burned'),
 ('BLDGMAINT', 'Park - Other/Complex'),
 ('KOCB', 'Park - Landscape Maintenance'),
 ('TRAFFIC_ENGIN', 'TE - Other Traffic Engineering Issues'),
 ('WATERSHED', 'Watershed - Illegal Dumping in a Creek'),
 ('ELECTRICAL', 'Utility - Lid - Missing or Broken'),
 ('OTHER', 'Sewers - Blockage'),
 ('DRAINAGE', 'Streets - Potholes/Depression'),
 ('TREES', 'Tree - Permit'),
 ('TRAFFIC', 'TE - Parking (On Street)'),
 ('PARKING', 'TE - Parking - Blue Curb (Non-Residential)'),
 ('OTHER', 'City Bldg - Structural Issue'),
 ('OTHER', 'Traffic - Sign Down'),
 ('RECYCLING', 'Garbage - Missed Pickup - Backyard'),
 ('PARKS', 'City Bldg - Structural Issue'),
 ('KOCB', 'Illegal Dumping - debris, appliances, etc.'),
 ('RECYCLING', 'Yard Trimmings - Missed Pickup - Backyard'),
 ('ELECTRICAL', 'Inspections - Utility-Related Infrastructure'),
 ('HOMELESS EMT', 'Litter in Parks'),
 ('PARKING', 'Parking - Abandoned Vehicle'),
 ('BLDGMAINT', 'Litter in Parks'),
 ('BLDGMAINT', 'Graffiti (report from SeeClickFix)'),
 ('ELECTRICAL', 'Park - Lighting'),
 ('OTHER', 'Park - Sign'),
 ('ROW_STREETSW', 'Curb Ramp - Install/Repair - ADA Request'),
 ('RECYCLING', 'Yard Trimmings - Missed Pickup - Whole Block'),
 ('STREETSW', 'Inspections - Utility-Related Infrastructure'),
 ('STREETSW', 'Streets - Mill & Fill'),
 ('RECYCLING', 'Compost - Contamination Question/Concern'),
 ('OTHER', 'Park - Fence'),
 ('OTHER', 'Traffic - Sign Damage'),
 ('TREES', 'Graffiti on OTHER'),
 ('RECYCLING', 'Recycling - Oil Kit Missed'),
 ('ILLDUMP', 'Code Enforcement'),
 ('BLDGMAINT', 'Park - Landscape Maintenance'),
 ('OTHER', 'Illegal Dumping - debris, appliances, etc.'),
 ('GRAFFITI', 'Graffiti on Traffic Sign(s)'),
 ('STREETSW', 'Inspections - Sewer Lateral'),
 ('ROW_STREETSW', 'Traffic - Repair Pavement Striping'),
 ('TRAFFIC', 'Other Engineering Issues'),
 ('BLDGMAINT', 'City Bldg - Vandalism'),
 ('TRAFFIC_ENGIN', 'Traffic - Sign Damage'),
 ('ILLDUMP', 'Obstruction (Construction) - Sidewalk'),
 ('PARKS', 'City Bldg - Plumbing'),
 ('TRAFFIC_ENGIN', 'Traffic - Other/Complex'),
 ('DRAINAGE', 'Sewers - Blockage'),
 ('OTHER', 'City Bldg - Electrical Inside/Outside'),
 ('ROW_INSPECTORS', 'Traffic - Repair Pavement Striping'),
 ('BLDGMAINT', 'Graffiti on Street, Street Light, Traffic Signal,'),
 ('RECYCLING', 'Garbage - Bulky Missed Pickup'),
 ('BLDGMAINT', 'Park - Ballfields'),
 ('KOCB', 'Street Medians (Landscaped)'),
 ('PARKS', 'Litter - Street Litter Container - Broken'),
 ('PARKS', 'Illegal Dumping – mattress/boxspring'),

In [7]:
Oakland_311_dropnan = Oakland_311.dropna(subset=['REQADDRESS'])
Oakland_311_dropnan['X'] = Oakland_311_dropnan['REQADDRESS'].str.split(',').str[0].str.split('(').str[1]
Oakland_311_dropnan['Y'] = Oakland_311_dropnan['REQADDRESS'].str.split(',').str[1].str.split(')').str[0]
Oakland_311_dropnan.head(3)

C:\Users\jduan\AppData\Local\Temp\ipykernel_2940\2455219464.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Oakland_311_dropnan['X'] = Oakland_311_dropnan['REQADDRESS'].str.split(',').str[0].str.split('(').str[1]
C:\Users\jduan\AppData\Local\Temp\ipykernel_2940\2455219464.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Oakland_311_dropnan['Y'] = Oakland_311_dropnan['REQADDRESS'].str.split(',').str[1].str.split(')').str[0]

,REQUESTID,DATETIMEINIT,SOURCE,DESCRIPTION,REQCATEGORY,REQADDRESS,STATUS,REFERREDTO,DATETIMECLOSED,SRX,SRY,COUNCILDISTRICT,BEAT,PROBADDRESS,City,State,Zipcode,X,Y
3,1319572,07/28/2023 08:57:26 AM,SeeClickFix,Parking - Enforcement,PARKING,"(37.7348199929233, -122.2006649756992)",OPEN,NaN,NaN,6069899.260,2094495.012,CCD7,31X,LEET DR,Oakland,CA,94621.0,37.7348199929233,-122.2006649756992
4,1319421,07/27/2023 03:53:54 PM,Phone,Parking (On Street),PARKING,"(37.80267929404058, -122.26696109306175)",OPEN,NaN,NaN,6051197.686,2119554.754,CCD3,04X,272 14TH ST,Oakland,CA,94612.0,37.80267929404058,-122.26696109306175
5,1028664,07/20/2020 10:38:32 AM,Phone,Tree - Permit,STREETSW,"(37.79211911541205, -122.24761294408194)",OPEN,NaN,NaN,6056714.845,2115605.265,CCD2,19X,1524 11TH AVE,Oakland,CA,94606.0,37.79211911541205,-122.24761294408194

In [8]:
Oakland_311_dropnan['DATETIMEINIT'] = pd.to_datetime(Oakland_311_dropnan['DATETIMEINIT'], format='%m/%d/%Y %I:%M:%S %p')
Oakland_311_dropnan['Year'] = Oakland_311_dropnan['DATETIMEINIT'].dt.year

C:\Users\jduan\AppData\Local\Temp\ipykernel_2940\1060279567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Oakland_311_dropnan['DATETIMEINIT'] = pd.to_datetime(Oakland_311_dropnan['DATETIMEINIT'], format='%m/%d/%Y %I:%M:%S %p')
C:\Users\jduan\AppData\Local\Temp\ipykernel_2940\1060279567.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Oakland_311_dropnan['Year'] = Oakland_311_dropnan['DATETIMEINIT'].dt.year

In [9]:
Oakland_311_dropnan['Year'].value_counts()

Year
2019    109763
2020    102522
2023    101982
2021     95130
2022     87678
2017     79446
2018     77066
2016     74372
2015     65588
2014     60769
2024     43935
2013     22863
Name: count, dtype: int64

In [11]:
Oakland_311_dropnan_2015 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2015]
Oakland_311_dropnan_2016 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2016]
Oakland_311_dropnan_2017 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2017]
Oakland_311_dropnan_2018 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2018]
Oakland_311_dropnan_2019 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2019]
Oakland_311_dropnan_2020 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2020]
Oakland_311_dropnan_2021 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2021]
Oakland_311_dropnan_2022 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2022]
Oakland_311_dropnan_2023 = Oakland_311_dropnan[Oakland_311_dropnan['Year'] == 2023]

In [15]:
Oakland_311_dropnan_2021

,REQUESTID,DATETIMEINIT,SOURCE,DESCRIPTION,REQCATEGORY,REQADDRESS,STATUS,REFERREDTO,DATETIMECLOSED,SRX,SRY,COUNCILDISTRICT,BEAT,PROBADDRESS,City,State,Zipcode,X,Y,Year
16,1099500,2021-03-25 11:28:22,Phone,Contractor Blocking Street/Sidewalk/Parking,ROW_INSPECTORS,"(37.8077838944387, -122.25353748070533)",CLOSED,NaN,07/31/2023 12:13:40 PM,6.055110e+06,2.121340e+06,CCD3,14X,491 BELLEVUE AVE,Oakland,CA,94610.0,37.8077838944387,-122.25353748070533,2021
17,1169118,2021-12-06 12:29:04,SeeClickFix,Street Light - Request for New/Upgrade,ELECTRICAL,"(37.7857600395092, -122.23331990807047)",UNFUNDED,NaN,NaN,6.060801e+06,2.113213e+06,CCD2,18X,E 17TH ST & 23RD AVE,Oakland,CA,94601.0,37.7857600395092,-122.23331990807047,2021
32,1117000,2021-05-28 10:33:53,Phone,Contractor Blocking Street/Sidewalk/Parking,ROW_INSPECTORS,"(37.811050454391285, -122.292938807557)",CLOSED,NaN,07/31/2023 12:13:43 PM,6.043752e+06,2.122745e+06,CCD3,02Y,1451 14TH ST,Oakland,CA,94607.0,37.811050454391285,-122.292938807557,2021
42,1152619,2021-10-03 20:24:05,SeeClickFix,Utility - Trench - Paving Issue,ROW_INSPECTORS,"(37.811912426145206, -122.27535182625705)",REFERRED,"ROW_SHOES, PG&E",NaN,6.048838e+06,2.122962e+06,CCD3,05X,2116 BRUSH ST,Oakland,CA,94612.0,37.811912426145206,-122.27535182625705,2021
51,1172746,2021-12-21 10:19:53,SeeClickFix,Streets - Potholes/Depression,STREETSW,"(37.79474119099074, -122.27497547670836)",OPEN,NaN,NaN,6.048828e+06,2.116709e+06,CCD3,01X,370 EMBARCADERO W,Oakland,CA,94607.0,37.79474119099074,-122.27497547670836,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479179,1172806,2021-12-21 11:57:27,Phone,TE - Traffic Safety (non-emergency),TRAFFIC_ENGIN,"(37.85034503664112, -122.25237680057916)",WOCREATE,NaN,NaN,6.055736e+06,2.136829e+06,CCD1,12Y,63RD ST & COLLEGE AVE,Oakland,CA,94618.0,37.85034503664112,-122.25237680057916,2021
479180,1164333,2021-11-15 13:14:10,SeeClickFix,"Illegal Dumping - debris, appliances, etc.",ILLDUMP,"(37.75467833426451, -122.14964999886747)",CANCEL,NaN,NaN,6.084777e+06,2.101461e+06,NaN,NaN,9765 MOUNTAIN BLVD,Oakland,CA,NaN,37.75467833426451,-122.14964999886747,2021
479181,1172029,2021-12-17 12:22:29,SeeClickFix,City Bldg - Structural Issue,BLDGMAINT,"(37.76546200285843, -122.1996369753754)",CLOSED,NaN,10/13/2022 02:49:38 PM,6.070399e+06,2.105645e+06,CCD6,27Y,DIGITAL ARTS AND CULINARY ACADEMY RECREATION C...,Oakland,CA,94621.0,37.76546200285843,-122.1996369753754,2021
479183,1166422,2021-11-23 13:14:20,SeeClickFix,"Illegal Dumping - debris, appliances, etc.",ILLDUMP,"(37.81223035631463, -122.29513343005401)",CLOSED,NaN,11/29/2021 07:47:20 PM,6.043126e+06,2.123187e+06,CCD3,05Y,1650 14TH ST,Oakland,CA,94607.0,37.81223035631463,-122.29513343005401,2021
479184,1170336,2021-12-10 15:56:19,SeeClickFix,Illegal Dumping – mattress/boxspring,ILLDUMP,"(37.788265042885406, -122.24720680740823)",CLOSED,NaN,12/14/2021 07:47:54 PM,6.056806e+06,2.114200e+06,CCD2,19X,E 12TH ST & E 8TH ST,Oakland,CA,94606.0,37.788265042885406,-122.24720680740823,2021

In [17]:
Oakland_311_dropnan_2015.to_csv('../Data/Oakland_311_dropnan_2015.csv')
Oakland_311_dropnan_2016.to_csv('../Data/Oakland_311_dropnan_2016.csv')
Oakland_311_dropnan_2017.to_csv('../Data/Oakland_311_dropnan_2017.csv')
Oakland_311_dropnan_2018.to_csv('../Data/Oakland_311_dropnan_2018.csv')
Oakland_311_dropnan_2019.to_csv('../Data/Oakland_311_dropnan_2019.csv')
Oakland_311_dropnan_2020.to_csv('../Data/Oakland_311_dropnan_2020.csv')
Oakland_311_dropnan_2021.to_csv('../Data/Oakland_311_dropnan_2021.csv')

In [18]:
# 把这些数据导入到arcgis pro得到311 points spjoin CB in Oakland City

### 311 spjoin CB -> 每个census block不同类别的311 requests的个数  
try:  
1.count/population  
2.count/area

In [19]:
import geopandas as gpd

In [23]:
OAK311_spjoin_CB_2015 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2015_projected_spjoinCB.shp')
OAK311_spjoin_CB_2016 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2016_projected_spjoinCB.shp')
OAK311_spjoin_CB_2017 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2017_projected_spjoinCB.shp')
OAK311_spjoin_CB_2018 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2018_projected_spjoinCB.shp')
OAK311_spjoin_CB_2019 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2019_projected_spjoinCB.shp')
OAK311_spjoin_CB_2020 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2020_projected_spjoinCB.shp')
OAK311_spjoin_CB_2021 = gpd.read_file('../Data/311_Oakland/Oakland_311point_spjoin_CB/Oakland_311_dropnan_2021_projected_spjoinCB.shp')

In [24]:
OAK311_spjoin_CB_2021

,Join_Count,TARGET_FID,REQUESTID,DATETIMEIN,SOURCE,DESCRIPTIO,REQCATEGOR,REQADDRESS,STATUS,REFERREDTO,...,MTFCC10,UR10,UACE10,UATYP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,1,1,1099500,2021-03-25,Phone,Contractor Blocking Street/Sidewalk/Parking,ROW_INSPECTORS,"(37.8077838944387, -122.25353748070533)",CLOSED,None,...,G5040,U,78904,U,S,9521.0,0.0,+37.8082233,-122.2534237,POINT (6055110.091 2121340.189)
1,1,2,1169118,2021-12-06,SeeClickFix,Street Light - Request for New/Upgrade,ELECTRICAL,"(37.7857600395092, -122.23331990807047)",UNFUNDED,None,...,G5040,U,78904,U,S,923.0,0.0,+37.7861598,-122.2329324,POINT (6060801.289 2113213.377)
2,1,3,1117000,2021-05-28,Phone,Contractor Blocking Street/Sidewalk/Parking,ROW_INSPECTORS,"(37.811050454391285, -122.292938807557)",CLOSED,None,...,G5040,U,78904,U,S,11387.0,0.0,+37.8104783,-122.2925164,POINT (6043752.119 2122745.069)
3,1,4,1152619,2021-10-03,SeeClickFix,Utility - Trench - Paving Issue,ROW_INSPECTORS,"(37.811912426145206, -122.27535182625705)",REFERRED,"ROW_SHOES, PG&E",...,G5040,U,78904,U,S,47497.0,0.0,+37.8110416,-122.2752282,POINT (6048837.697 2122962.025)
4,1,5,1172746,2021-12-21,SeeClickFix,Streets - Potholes/Depression,STREETSW,"(37.79474119099074, -122.27497547670836)",OPEN,None,...,G5040,U,78904,U,S,11013.0,0.0,+37.7949542,-122.2748000,POINT (6048827.817 2116708.644)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95125,1,95126,1172806,2021-12-21,Phone,TE - Traffic Safety (non-emergency),TRAFFIC_ENGIN,"(37.85034503664112, -122.25237680057916)",WOCREATE,None,...,G5040,U,78904,U,S,720.0,0.0,+37.8499339,-122.2523612,POINT (6055735.520 2136828.763)
95126,1,95127,1164333,2021-11-15,SeeClickFix,"Illegal Dumping - debris, appliances, etc.",ILLDUMP,"(37.75467833426451, -122.14964999886747)",CANCEL,None,...,G5040,U,78904,U,S,18133.0,0.0,+37.7555887,-122.1491413,POINT (6084776.746 2101460.643)
95127,1,95128,1172029,2021-12-17,SeeClickFix,City Bldg - Structural Issue,BLDGMAINT,"(37.76546200285843, -122.1996369753754)",CLOSED,None,...,G5040,U,78904,U,S,39483.0,0.0,+37.7662502,-122.1997885,POINT (6070399.108 2105645.130)
95128,1,95129,1166422,2021-11-23,SeeClickFix,"Illegal Dumping - debris, appliances, etc.",ILLDUMP,"(37.81223035631463, -122.29513343005401)",CLOSED,None,...,G5040,U,78904,U,S,11054.0,0.0,+37.8126751,-122.2956459,POINT (6043126.491 2123186.773)
95129,1,95130,1170336,2021-12-10,SeeClickFix,Illegal Dumping – mattress/boxspring,ILLDUMP,"(37.788265042885406, -122.24720680740823)",CLOSED,None,...,G5040,U,78904,U,S,1087.0,0.0,+37.7883255,-122.2470380,POINT (6056805.981 2114199.965)

In [27]:
OAK311_spjoin_CB_2021['Join_Count'].value_counts(dropna = False)

Join_Count
1    94936
0      193
2        1
Name: count, dtype: int64

In [29]:
CBG_df = pd.read_csv('../Data/CBG_pop_2010/DECENNIALPL2010.P1-Data.csv')
CBG_df = CBG_df.iloc[1:,:]
CBG_df = CBG_df[["GEO_ID","P001001"]]
CBG_df["CBG_ID"] = CBG_df["GEO_ID"].apply(lambda x:x.split("US")[1].strip()[1:])
CBG_df["P001001"] = pd.to_numeric(CBG_df["P001001"], errors='coerce')
grouped_df = CBG_df.groupby("CBG_ID")["P001001"].sum().reset_index()
grouped_df.rename(columns={"P001001": "CBG_pop"}, inplace=True)
grouped_df

           CBG_ID  CBG_pop
0     60014001001     2937
1     60014002001     1018
2     60014002002      956
3     60014003001     1078
4     60014003002     1298
...           ...      ...
1042  60014517043      872
1043  60019819001       38
1044  60019820001       71
1045  60019832001      540
1046  60019900000        0

[1047 rows x 2 columns]

In [31]:
# # 删掉REQCATEGOR为NAN的行
# OAK311_spjoin_CB_2015_dropna = OAK311_spjoin_CB_2015_dropna.dropna(subset = ['REQCATEGOR'])
# pivot_table = OAK311_spjoin_CB_2015_dropna.pivot_table(index='GEOID10', columns='REQCATEGOR', aggfunc='size', fill_value=0).reset_index()
# pivot_table['sum_count'] = pivot_table.iloc[:,1:].sum(axis=1)

datasets = [OAK311_spjoin_CB_2015, OAK311_spjoin_CB_2016, OAK311_spjoin_CB_2017,
            OAK311_spjoin_CB_2018, OAK311_spjoin_CB_2019, OAK311_spjoin_CB_2020,
            OAK311_spjoin_CB_2021]
# datasets = [OAK311_spjoin_CB_2021]
#print(len(OAK311_spjoin_CB_2021))

pivot_tables = []

# 循环处理每一个数据集
for data in datasets:
    data = data.dropna(subset=['GEOID10'])
    data_dropna = data.dropna(subset=['REQCATEGOR'])
      
    pivot_table = data_dropna.pivot_table(index='GEOID10', columns='REQCATEGOR', aggfunc='size', fill_value=0).reset_index()
    pivot_table['sum_count'] = pivot_table.iloc[:, 1:].sum(axis=1)
    pivot_tables.append(pivot_table)

In [32]:
OAK311_categories_count_CB_2015 = pivot_tables[0]
OAK311_categories_count_CB_2016 = pivot_tables[1]
OAK311_categories_count_CB_2017 = pivot_tables[2]
OAK311_categories_count_CB_2018 = pivot_tables[3]
OAK311_categories_count_CB_2019 = pivot_tables[4]
OAK311_categories_count_CB_2020 = pivot_tables[5]
OAK311_categories_count_CB_2021 = pivot_tables[6]

In [35]:
OAK311_categories_count_CB_2015

REQCATEGOR,GEOID10,BLDGMAINT,CUT_CLEAN,CW_DIT_GIS,DRAINAGE,ELECTRICAL,FIRE,GRAFFITI,HE_CLEAN,ILLDUMP,...,ROW_INSPECTORS,ROW_STREETSW,SEWERS,STREETSW,SURVEY,TRAFFIC,TRAFFIC_ENGIN,TREES,WATERSHED,sum_count
0,060014001001000,0,0,0,0,0,0,0,0,2,...,0,0,0,1,0,0,0,0,0,3
1,060014001001001,0,0,0,0,0,0,0,0,2,...,0,0,0,3,0,0,0,0,0,6
2,060014001001002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,4
3,060014001001007,0,0,0,0,0,0,0,0,1,...,0,0,6,2,0,1,0,0,0,11
4,060014001001008,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5341,060019832001051,1,0,0,0,0,0,0,0,9,...,1,0,0,1,0,1,0,0,0,14
5342,060019832001052,0,0,0,0,0,0,0,0,7,...,0,0,0,3,0,0,0,3,0,17
5343,060019832001053,0,0,0,0,0,0,0,0,4,...,0,0,0,3,0,0,0,1,0,8
5344,060019832001054,0,0,0,0,0,0,1,0,2,...,0,1,1,1,0,2,2,1,0,18
5345,060019832001055,0,0,0,1,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,5

In [37]:
OAK311_categories_count_CB_2015["CBG_ID"] = OAK311_categories_count_CB_2015["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2015_merge = OAK311_categories_count_CB_2015.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2016["CBG_ID"] = OAK311_categories_count_CB_2016["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2016_merge = OAK311_categories_count_CB_2016.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2017["CBG_ID"] = OAK311_categories_count_CB_2017["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2017_merge = OAK311_categories_count_CB_2017.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2018["CBG_ID"] = OAK311_categories_count_CB_2018["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2018_merge = OAK311_categories_count_CB_2018.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2019["CBG_ID"] = OAK311_categories_count_CB_2019["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2019_merge = OAK311_categories_count_CB_2019.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2020["CBG_ID"] = OAK311_categories_count_CB_2020["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2020_merge = OAK311_categories_count_CB_2020.merge(grouped_df, on = 'CBG_ID', how = 'left')
OAK311_categories_count_CB_2021["CBG_ID"] = OAK311_categories_count_CB_2021["GEOID10"].apply(lambda x:x[1:12])
OAK311_categories_count_CB_2021_merge = OAK311_categories_count_CB_2021.merge(grouped_df, on = 'CBG_ID', how = 'left')

In [39]:
# OAK311_categories_count_CB_all_years = [
#     OAK311_categories_count_CB_2015,
#     OAK311_categories_count_CB_2016,
#     OAK311_categories_count_CB_2017,
#     OAK311_categories_count_CB_2018,
#     OAK311_categories_count_CB_2019,
#     OAK311_categories_count_CB_2020,
#     OAK311_categories_count_CB_2021
# ]

OAK311_categories_count_CB_2021_merge#.columns[1:-3]

,GEOID10,ABANDONED AUTO,BLDGMAINT,CUT_CLEAN,CW_DIT_GIS,DRAINAGE,ELECTRICAL,ENVIRON_ENF,FACILITIES,FIRE,...,SEWERS,STREETSW,SURVEY,TRAFFIC,TRAFFIC_ENGIN,TREES,WATERSHED,sum_count,CBG_ID,CBG_pop
0,060014001001000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,60014001001,2937
1,060014001001002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,60014001001,2937
2,060014001001007,0,0,0,0,0,0,0,0,0,...,4,2,0,2,0,5,0,18,60014001001,2937
3,060014001001008,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2,60014001001,2937
4,060014001001011,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,7,60014001001,2937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5581,060019832001051,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,5,60019832001,540
5582,060019832001052,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,7,60019832001,540
5583,060019832001053,0,0,0,0,0,0,0,0,0,...,3,1,0,0,0,0,0,8,60019832001,540
5584,060019832001054,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,7,60019832001,540
5585,060019832001055,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,60019832001,540

In [41]:
OAK311_categories_count_CB_2015_merge.to_csv('../Data/311_Oakland/Oakland311_2015_pivotTable.csv')
OAK311_categories_count_CB_2016_merge.to_csv('../Data/311_Oakland/Oakland311_2016_pivotTable.csv')
OAK311_categories_count_CB_2017_merge.to_csv('../Data/311_Oakland/Oakland311_2017_pivotTable.csv')
OAK311_categories_count_CB_2018_merge.to_csv('../Data/311_Oakland/Oakland311_2018_pivotTable.csv')
OAK311_categories_count_CB_2019_merge.to_csv('../Data/311_Oakland/Oakland311_2019_pivotTable.csv')
OAK311_categories_count_CB_2020_merge.to_csv('../Data/311_Oakland/Oakland311_2020_pivotTable.csv')
OAK311_categories_count_CB_2021_merge.to_csv('../Data/311_Oakland/Oakland311_2021_pivotTable.csv')